services:
  - type: web
    name: calculator-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://calculator-nu-smoky-22.vercel.app
    healthCheckPath: /api/history
